apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp1-deployment
  labels:
    app: testapp1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: testapp1
  template:
    metadata:
      labels:
        app: testapp1
    spec:
      containers:
        - name: testapp1
          image: radumarinoiu/testapp1
          ports:
          - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: testapp1-service
spec:
  type: NodePort
  selector:
    app: testapp1
  ports:
    - protocol: TCP
      nodePort: 30001
      port: 80
      targetPort: 5000