apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp2-deployment
  labels:
    app: testapp2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: testapp2
  template:
    metadata:
      labels:
        app: testapp2
    spec:
      containers:
        - name: testapp2
          image: radumarinoiu/testapp2
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: testapp2-service
spec:
  type: NodePort
  selector:
    app: testapp2
  ports:
    - protocol: TCP
      nodePort: 30002
      port: 80
      targetPort: 5000